# Generated by Django 6.0.3 on 2026-03-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
